# Configuration for pre-commit hooks, see: https://pre-commit.com/
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    # docs: https://flake8.pycqa.org/en/latest/user/using-hooks.html?highlight=commit
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies: [flake8-pyproject]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          [
            --config-file,
            pyproject.toml,
            -p,
            annodize,
            --ignore-missing-imports,
          ]
  # SEE: https://pre-commit.com/#repository-local-hooks
  # - repo: local
  #   hooks:
  #     - id: foo
  #       name: foo
  #       entry: foo
  #       language: system
  #       description: "Example local hook, see https://pre-commit.com/#repository-local-hooks"
