name: annoframe
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  # might be faster
  - pandas=1.4
  - pyspark=3.2
  # for examples?
  - jupyter
  - pip:
      - "-e .[dev,pandas,pyspark,docs]"
      - beartype
      - typeguard
      - runtype
